version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html
hooks:
   BeforeInstall:
    - location: deployment/install_dependencies.sh
      timeout: 300
      runas: root
   AfterInstall:
    - location: deployment/deploy_laravel.sh
      timeout: 300
      runas: root
    - location: deployment/change_permissions.sh
      timeout: 300
      runas: root
    - location: deployment/restartapache.sh
      runas: root
   ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
   ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root